In [1]:
import numpy as np
import pandas as pd
import pickle 
from sklearn.cluster import MeanShift,estimate_bandwidth, DBSCAN
import random
import h5py
import datetime

In [2]:
seed = 140
random.seed(seed)

In [ ]:
a = np.random.rand(100000,5,4)
a = np.round(a,3)
a.shape

In [ ]:
dict_test = {'a': np.ones((100,100)), 'b': np.zeros((100,100))}
hf = h5py.File('dict_data.h5', 'w')
dict_group = hf.create_group('dict_data')
for k, v in dict_test.items():
    dict_group[k] = v
hf.close()


In [ ]:
dict_new = {}
file = h5py.File('dict_data.h5', 'r')
dict_group_load = file['dict_data']
dict_group_keys = dict_group_load.keys()
for k in dict_group_keys:
    dict_new[k]= dict_group_load[k][:]


In [ ]:
def save_h5_file(array):
    file_name = 'rand_data.h5'
    dataset_name = 'dataset_1'
    h5f = h5py.File(file_name, 'w')
    h5f.create_dataset(dataset_name, data=array)
    h5f.close()
    return file_name,dataset_name



In [ ]:
f_name, d_name = save_h5_file(a)

In [ ]:
def load_h5_file(file_name,dataset_name):
    h5f = h5py.File(file_name,'r')
    a = h5f[dataset_name][:]
    h5f.close()
    return a

In [ ]:
data = load_h5_file(f_name, d_name)
data.shape

In [ ]:
q = 0.2
l = len(data)
bs = estimate_bandwidth(data, quantile=q, n_samples=l)

In [ ]:
d = {}
for i in range(l):
    key = list(a[i].reshape(-1))
    d[tuple(key)] = i

In [ ]:
for key in d.keys():
    print(len(key), d[key])

In [ ]:
with open('index.pkl', 'wb') as f:
    pickle.dump(d, f)

In [ ]:
with open('index.pkl', 'rb') as f:
    d1 = pickle.load(f)

In [ ]:
X = np.array([[1, 1], [2, 1], [1, 0],[4, 7], [3, 5], [3, 6]])
clusters = MeanShift(bandwidth=0.1).fit(X)

In [ ]:
clusters.labels_

In [ ]:
clusters

In [ ]:
a = list(d.keys())
a

In [ ]:
clusters1 = MeanShift(bandwidth=1.3).fit(a)
clusters1.labels_, clusters1.cluster_centers_.shape

In [ ]:
# cluster_centers_
# labels_
# n_iter
# n_features_in
# feature_names_in

In [ ]:
def random_clustering(n):
    a = np.random.rand(n,5,4)
    d,l = {}, len(a)
    for i in range(l):
        key = list(a[i].reshape(-1))
        d[tuple(key)] = i
    idx = list(d.keys())
    clusters1 = MeanShift(n_jobs=-1).fit(idx)
    return clusters1

In [ ]:
n_points = [100, 1000, 10000, 100000, 500000, 1000000, 200000]
for n in n_points:
    st = datetime.datetime.now()
    c = random_clustering(n)
    et = datetime.datetime.now()
    print("n_points:",len(c.labels_),",n_clusters:", len(c.cluster_centers_),",time:",(et-st))

In [ ]:
20

In [3]:
def random_clustering2(n):
    a = np.random.rand(n,5,4)
    d,l = {}, len(a)
    for i in range(l):
        key = list(a[i].reshape(-1))
        d[tuple(key)] = i
    idx = list(d.keys())
    clusters = DBSCAN(n_jobs=-1).fit(idx)

    reduced_index = {}
    cluster_labels = c.labels_
    for i in range(0,len(cluster_labels)):
        cluster = cluster_labels[i]
        centroid = tuple(cluster_centers[cluster])
        doc = index[layouts[i]]
        if centroid in reduced_index:
            reduced_index[centroid].add(doc)
        else:
            reduced_index[centroid] = set([doc])
        if i%100==0:
            print("building inverted index, completed {}%".format(np.round((i+1)/len(cluster_labels),2)))
    s2 = datetime.datetime.now()

    return reduced_index

In [5]:
n_points = [100, 1000, 10000, 100000, 500000, 1000000, 2000000, 5000000, 10000000]
for n in n_points:
    st = datetime.datetime.now()
    c = random_clustering2(n)
    et = datetime.datetime.now()
    # core_sample_indices, components, labels, n_features_in, feature_names_in = c
    # print("n_points:",len(c.labels_),",n_clusters:", len(c.cluster_centers_),",time:",(et-st))
    
    print(c.core_sample_indices_, c.components_, len(c.labels_), c.n_features_in_,", time:",(et-st))

[] [] 100 20 , time: 0:00:00.004154
[] [] 1000 20 , time: 0:00:00.014817
[] [] 10000 20 , time: 0:00:00.097380
[] [] 100000 20 , time: 0:00:01.372730
[] [] 500000 20 , time: 0:00:20.531812
[] [] 1000000 20 , time: 0:01:10.788486
[] [] 2000000 20 , time: 0:04:02.029747
[] [] 5000000 20 , time: 0:23:18.145466
[1046894 2408208 2610379 2757026 4940078 6694026 8584708 9364195 9903915] [[0.93862146 0.46146347 0.80941835 0.89203573 0.45239351 0.38616828
  0.46343062 0.95842051 0.49072665 0.70803222 0.64377794 0.51990485
  0.6078462  0.72940898 0.36872079 0.8909236  0.08283011 0.42932025
  0.35007553 0.75764906]
 [0.25980906 0.72696682 0.21487045 0.39243281 0.86371284 0.14381491
  0.80146356 0.77564843 0.66189305 0.31394285 0.81058618 0.61366562
  0.78489118 0.19252587 0.57617534 0.43730717 0.59258106 0.15903893
  0.78951066 0.31727258]
 [0.67569241 0.60998039 0.33458048 0.3124528  0.88840088 0.18450014
  0.83648298 0.54202947 0.39402385 0.31463385 0.27721207 0.92812044
  0.10598967 0.83993744

In [6]:
c.n_features_in_

20

In [8]:
len(c.labels_)

10000000

In [10]:
c.labels_.min(),c.labels_.max()

(-1, 8)

In [13]:
np.unique(c.labels_)

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [ ]:
a = np.random.random(size=(100,20))


In [ ]:
b.shape

In [ ]:
np.allclose(a,b)

In [43]:
def random_clustering(n, max_samples=10000):
    a = np.random.rand(n,5,4)
    d,l = {}, len(a)
    for i in range(l):
        key = list(a[i].reshape(-1))
        d[tuple(key)] = i
    idx = list(d.keys())
    ms = MeanShift(n_jobs=-1)
    for i in range(0, n, max_samples):
        minibatch = idx[i:i+max_samples]
        ms.fit(minibatch)
        print(i)
    clusters = []
    for p in idx:
        p1 = [np.array(p)]
        cluster = ms.predict(p1)
        clusters.append(cluster)
    return clusters

In [44]:
random_clustering(1000000)

0
10000
20000
30000
40000
50000
60000
70000
80000
90000
100000
110000
120000
130000
140000
150000
160000
170000
180000
190000
200000
210000
220000
230000
240000
250000
260000
270000
280000
290000
300000
310000
320000
330000
340000
350000
360000
370000
380000
390000
400000
410000
420000
430000
440000
450000
460000
470000
480000
490000
500000
510000
520000
530000
540000
550000
560000
570000
580000
590000
600000
610000
620000
630000
640000
650000
660000
670000
680000
690000
700000
710000
720000
730000
740000
750000
760000
770000
780000
790000
800000
810000
820000
830000
840000
850000
860000
870000
880000
890000
900000
910000
920000
930000
940000
950000
960000
970000
980000
990000


[array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),

In [6]:
random_clustering(1000)

1000


MeanShift(n_jobs=-1)

In [7]:
a = np.random.rand(1000,5,4)
d,l = {}, len(a)
for i in range(l):
    key = list(a[i].reshape(-1))
    d[tuple(key)] = i
idx = list(d.keys())

In [13]:
l = len(idx)//2
s1, s2 = idx[:l],idx[l:]

In [14]:
len(s1), len(s2)

(500, 500)

In [19]:
ms = MeanShift(n_jobs=-1)
ms.fit(s1)
ms.fit(s2)

MeanShift(n_jobs=-1)

In [34]:
for p in idx:
    p1 = [np.array(p)]
    cluster = ms.predict(p1)
    print(cluster)

[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]


In [35]:
ms.cluster_centers_

array([[0.47990212, 0.48757817, 0.48953918, 0.49022262, 0.5118639 ,
        0.50292638, 0.49168403, 0.48719758, 0.46752338, 0.52055771,
        0.4796259 , 0.46333485, 0.49394344, 0.49246411, 0.49138591,
        0.47243286, 0.49500046, 0.49940733, 0.49183483, 0.48647999]])

In [38]:
maxsamples = 100
for i in range(0, 80, maxsamples):
    print(i, i+maxsamples)

0 100


In [78]:
def whole_clustering(data):
    index,l = {}, len(data)
    for i in range(l):
        key = list(data[i].reshape(-1))
        index[tuple(key)] = i

    layouts = list(index.keys())
    clusterer = MeanShift()
    clusters = clusterer.fit(layouts) # type: ignore
    cluster_labels = clusters.labels_
    cluster_centers = clusters.cluster_centers_

    reduced_index = {}
    for i in range(0,len(cluster_labels)):
        cluster = cluster_labels[i]
        centroid = tuple(cluster_centers[cluster])
        doc = index[layouts[i]]
        if centroid in reduced_index:
            reduced_index[centroid].add(doc)
        else:
            reduced_index[centroid] = set([doc])
    print(i, len(cluster_centers[cluster]), )
    print(len(centroid),len(reduced_index))
    for key in reduced_index:
        print(len(key), len(reduced_index[key]), reduced_index[key])
        break
    
def bootstrap_clustering(data):
    index,l = {}, len(data)
    for i in range(l):
        key = list(data[i].reshape(-1))
        index[tuple(key)] = i
    layouts = list(index.keys())
    meanshift = MeanShift(n_jobs=-1)

    for i in range(0, len(index), 10000):
        minibatch = layouts[i:i+10000]
        meanshift.fit(minibatch)
    cluster_centers = meanshift.cluster_centers_

    reduced_index = {}
    for i,p in enumerate(layouts):
        p1 = [tuple(np.array(p))]
        cluster = meanshift.predict(p1)
        centroid = tuple(cluster_centers[cluster[0]])
        doc = index[layouts[i]]
        if centroid in reduced_index:
            reduced_index[centroid].add(doc)
        else:
            reduced_index[centroid] = set([doc])              

    print("p ", len(p))
    print("p1 ", len(p1), len(p1[0]))
    print("cluster ", cluster[0])
    print(len(centroid),len(reduced_index))
    for key in reduced_index:
        print(len(key), len(reduced_index[key]), reduced_index[key])
        break
    
data = np.random.rand(100,5,4)
whole_clustering(data)
print("======")
bootstrap_clustering(data)

99 20
20 1
20 100 {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99}
p  20
p1  1 20
cluster  0
20 1
20 100 {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99}
