In [1]:
import numpy as np
import cv2

In [2]:
Xa = (0.5,1)
Xb = (0.78,0.99)
Xc = (0.45, -0.2)

In [20]:
P1 = [[0.5,1,1],
      [0.78,0.99,1],
      [0.45, -0.2,1]]
P1

[[0.5, 1, 1], [0.78, 0.99, 1], [0.45, -0.2, 1]]

In [21]:
np.sign(P1)

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1., -1.,  1.]])

In [22]:
np.linalg.det(P1)

-0.3365000000000001

In [23]:
P2 = [[0.55,1.2,1],
      [0.7,0.9,1],
      [0.5, -0.1,1]]
P2

[[0.55, 1.2, 1], [0.7, 0.9, 1], [0.5, -0.1, 1]]

In [24]:
np.sign(P2)

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1., -1.,  1.]])

In [25]:
np.linalg.det(P2)

-0.2099999999999999

In [7]:
s1 = np.sign(P1)
s2 = np.sign(P2)
s1,s2

(array([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1., -1.,  1.]]),
 array([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1., -1.,  1.]]))

In [8]:
np.dot(s1,s2)

array([[ 3.,  1.,  3.],
       [ 3.,  1.,  3.],
       [ 1., -1.,  1.]])

In [9]:
np.matmul(s1,s2)

array([[ 3.,  1.,  3.],
       [ 3.,  1.,  3.],
       [ 1., -1.,  1.]])

In [17]:
def get_orientation(matrix):
   determinant = np.linalg.det(matrix)
   orientation = np.sign(determinant) 
   return orientation

def verfiy_orientation(P1,P2):
    s1 = get_orientation(P1)
    s2 = get_orientation(P2)
    verif = s1 * s2
    return int(verif)

In [16]:
verfiy_orientation(P1,P2)

1